@endpoint = {{host}}/auth

POST {{endpoint}}/signup
Content-Type: application/json

{
  "email": "james@test.com",
  "password": "testPassword"
}
###
PATCH {{endpoint}}/1
Content-Type: application/json

{
  "password": "newTestPassword"
}
###
GET {{endpoint}}/2

###
GET {{endpoint}}/search/james%40test.com

###
DELETE {{endpoint}}/1

